# Generated by Django 5.2.8 on 2026-04-20 03:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DMARCReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_name', models.CharField(blank=True, max_length=255)),
                ('org_email', models.EmailField(blank=True, max_length=254)),
                ('report_id', models.CharField(blank=True, max_length=255)),
                ('date_begin', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('domain_policy', models.CharField(blank=True, max_length=255)),
                ('policy_adkim', models.CharField(blank=True, max_length=10)),
                ('policy_aspf', models.CharField(blank=True, max_length=10)),
                ('policy_p', models.CharField(blank=True, max_length=20)),
                ('policy_sp', models.CharField(blank=True, max_length=20)),
                ('policy_pct', models.IntegerField(default=100)),
                ('raw_xml', models.TextField(blank=True)),
                ('source_email_subject', models.CharField(blank=True, max_length=500)),
                ('source_email_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('passed_messages', models.IntegerField(default=0)),
                ('failed_messages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmarc_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dmarc_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DMARCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField()),
                ('message_count', models.IntegerField(default=1)),
                ('disposition', models.CharField(choices=[('none', 'None'), ('quarantine', 'Quarantine'), ('reject', 'Reject')], default='none', max_length=20)),
                ('dkim_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('softfail', 'Softfail'), ('neutral', 'Neutral'), ('none', 'None'), ('temperror', 'Temperror'), ('permerror', 'Permerror')], default='none', max_length=20)),
                ('spf_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('softfail', 'Softfail'), ('neutral', 'Neutral'), ('none', 'None'), ('temperror', 'Temperror'), ('permerror', 'Permerror')], default='none', max_length=20)),
                ('envelope_to', models.CharField(blank=True, max_length=255)),
                ('envelope_from', models.CharField(blank=True, max_length=255)),
                ('header_from', models.CharField(blank=True, max_length=255)),
                ('dkim_domain', models.CharField(blank=True, max_length=255)),
                ('dkim_selector', models.CharField(blank=True, max_length=255)),
                ('dkim_human_result', models.TextField(blank=True)),
                ('spf_domain', models.CharField(blank=True, max_length=255)),
                ('spf_scope', models.CharField(blank=True, max_length=50)),
                ('geo_country', models.CharField(blank=True, max_length=100)),
                ('geo_city', models.CharField(blank=True, max_length=100)),
                ('geo_latitude', models.FloatField(blank=True, null=True)),
                ('geo_longitude', models.FloatField(blank=True, null=True)),
                ('geo_isp', models.CharField(blank=True, max_length=255)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('alert_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='reports.dmarcreport')),
            ],
            options={
                'db_table': 'dmarc_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('spf_fail', 'SPF Fail'), ('dkim_fail', 'DKIM Fail'), ('both_fail', 'SPF & DKIM Fail'), ('suspicious_ip', 'Suspicious IP'), ('policy_reject', 'Policy Reject')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('message_body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_detail', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='reports.dmarcrecord')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='reports.dmarcreport')),
            ],
            options={
                'db_table': 'alert_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('rua_email', models.EmailField(max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'domains',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'domain_name')},
            },
        ),
        migrations.AddField(
            model_name='dmarcreport',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.domain'),
        ),
        migrations.CreateModel(
            name='IMAPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=993)),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('use_ssl', models.BooleanField(default=True)),
                ('mailbox', models.CharField(default='INBOX', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imap_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IMAP Config',
                'db_table': 'imap_configs',
            },
        ),
    ]
