# Generated by Django 5.2.8 on 2026-04-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmarcreport',
            name='ai_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dmarcreport',
            name='ai_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dmarcreport',
            name='ai_findings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dmarcreport',
            name='ai_policy_advice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dmarcreport',
            name='ai_recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dmarcreport',
            name='ai_risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unknown', 'Unknown')], max_length=20),
        ),
        migrations.AddField(
            model_name='dmarcreport',
            name='ai_risk_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dmarcreport',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
    ]
