# Generated by Django 5.2.8 on 2026-04-28 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_dmarcreport_ai_analyzed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_enabled', models.BooleanField(default=False)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100)),
                ('notify_on_suspicious', models.BooleanField(default=True)),
                ('notify_on_any_fail', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_configs',
            },
        ),
    ]
